### ISSUE TITLE
Concevoir la communication avec l'API Découpage Administratif des communes

### ISSUE THREAD

**Issue by Sirmetana** [LouisPiel/TD2_Forecast_IW#5]
-Découvrir l'API Découpage Administratif des communes
-Lier l'API à notre projet
-Récupérer les valeurs dont on aura besoin dans d'autres issues

Testeur: Lukas (sirmetana)

**Comment by NekuaTicoz** [comment]
J'ai commencé à me renseigné sur les API grâce à ce lien : https://openclassrooms.com/fr/courses/6573181-adoptez-les-api-rest-pour-vos-projets-web/6817216-identifiez-les-avantages-d-une-api-rest

**Comment by NekuaTicoz** [comment]
acces rapide sur la page de l'api https://geo.api.gouv.fr/decoupage-administratif/communes

**Comment by NekuaTicoz** [comment]
https://fr.javascript.info/fetch aide api
https://curlconverter.com/javascript/ ct utile
